# Generated by Django 4.0.3 on 2022-03-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategories',
        ),
    ]
